title: Web Five

author: Claudio Corsi

navbar-links:
  About Me: "aboutme"

avatar: "/assets/img/avatar-icon.png"

social-network-links:
  email: clcorsi@yahoo.com
  github: ccorsi

rss-description: Claudio Corsi personal web site, all opinions are my own

share-links-active:
  twitter: false
  facebook: false
  linkenin: true
  vk: false

url-pretty: "Claudio Corsi GitHub Page"

excerpt_length: 50

feed_show_excerpt: true

feed_show_tags: true

post_search: true

edit_page_button: true

navbar-var-length: false

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
      toc: true
      before-content:
        - quotes.html # This includes the required script to display quotes
        - toc.html # This will include the <div id="toc"></div> element
      js:
        - /assets/js/toc.js  # This will generate the toc for the page
        - /assets/js/toc-handler.js # This will define which headers to include for the toc and add callback
        - /assets/js/quotes-handler.js # This is used to execute the quotes javascript command



theme: beautiful-jekyll-theme
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
