# This configuration file will contain site wide configuration entries that can be updated
# when one is developing one's web site.  The value of this file is that is can then be
# used as the official configuration file for a given generated web site.

# This will also be used to test what happens when you use this file to update the
# global properties of the genereated Jekyll web sites.  Specifically, the site attribute
# that is used throughout the web site generation.  The ones that could be updated with no
# issues will probably be the ones that aren't complex objects like arrays.

bootstrap:
  js:
    version: 5.3.3
    sri: sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH
  css:
    version: 5.3.3
    sri: sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH

# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha256-WeLjw8JYAtNUcyjqluHrkVYN1fpL7TtakwRhaRgUx8s=" crossorigin="anonymous"></script>
# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha256-gOQJIa9+K/XdfAuBkg2ONAdw5EnQbokw/s2b8BqsRFg=" crossorigin="anonymous"></script>
# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha256-YMa+wAM6QkVyz999odX7lPRxkoYAan8suedu4k2Zur8=" crossorigin="anonymous"></script>
# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha256-3gQJhtmj7YnV1fmtbVcnAV6eI4ws0Tr48bVZCThtCGQ=" crossorigin="anonymous"></script>